definitions:
  structures.Counting:
    properties:
      end_date:
        type: string
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  structures.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  structures.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /subscription/:
    get:
      description: List of all subscriptions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/structures.Subscription'
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Get All subscriptions
      tags:
      - Subscriptions
    post:
      consumes:
      - application/json
      description: Creating new subscription
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/structures.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: message + id
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid subscription format
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Create Subscription
      tags:
      - Subscriptions
  /subscription/{id}:
    delete:
      description: Delete subscription by ID
      parameters:
      - description: subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Delete subscription
      tags:
      - Subscriptions
    get:
      description: returns subscription by ID
      parameters:
      - description: subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structures.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Get one subscription by ID
      tags:
      - Subscriptions
    put:
      consumes:
      - application/json
      description: Update subscription by ID
      parameters:
      - description: subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/structures.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Update subscription
      tags:
      - Subscriptions
  /summ/:
    get:
      consumes:
      - application/json
      description: Returns the sum of all subscriptions filtered by date, user and
        service
      parameters:
      - description: Filters
        in: body
        name: counting
        required: true
        schema:
          $ref: '#/definitions/structures.Counting'
      produces:
      - application/json
      responses:
        "200":
          description: total
          schema:
            additionalProperties:
              format: float64
              type: number
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structures.ErrorResponse'
      summary: Get summ of subscriptions prices
      tags:
      - Sum
swagger: "2.0"
